development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: qna_forum_development
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: qna_forum_test
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: qna_forum_production
  pool: 5
  username: root
  password: fsysnsdr?,udw
  socket: /var/run/mysqld/mysqld.sock

